name: firebase_analytics
description: Flutter plugin for Google Analytics for Firebase, an app measurement
  solution that provides insight on app usage and user engagement on Android and iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics
version: 5.0.11

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebaseanalytics
        pluginClass: FirebaseAnalyticsPlugin
      ios:
        pluginClass: FLTFirebaseAnalyticsPlugin

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  e2e: ^0.2.1
  mockito: 3.0.0
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.0
  flutter_driver:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
